// src/readme.ts
//
// The README that carries the Session: one `<picture>` that swaps on the reader's theme, and the
// Session's text underneath it in a `<details>` block. `build` writes it; nothing here reads the
// filesystem or the network.
//
// THE TRANSCRIPT IS NOT DECORATION. The whole Session is one image (ADR 0004), so the picture
// exposes no text at all: no selection, no search, no screen reader, nothing for a client that
// will not render an SVG. The `<details>` block is the only path to the content for all of those,
// which is why the handle and the spinner's verb were given `textOnly` runs in the first place
// (src/rows.ts) and why `alt` is a short description rather than the Session retyped: the words
// are already here, as real text, directly below the picture.
//
// WHAT GITHUB ALLOWS, measured rather than remembered. GitHub sanitises README HTML, and the
// failure mode is invisible: the page still renders, just wrong. Re-verified 2026-10-02 by POSTing
// this exact markup to `https://api.github.com/markdown`, which is GitHub's own renderer behind
// its own sanitiser, and reading back what survived:
//
//   - `<picture>` with `<source media srcset>` survives intact, wrapped in `<themed-picture>`.
//   - `<img src alt width>` survives. GitHub injects `style="max-width: 100%"` itself and
//     auto-wraps the image in a link to its own src.
//   - `<details>` and `<summary>` survive, and a fenced code block inside them becomes
//     `<pre><code>`, which is what keeps the transcript's column grid aligned.
//   - An HTML comment is removed from the output entirely, so the generated-file notice at the
//     top costs the reader nothing.
//   - Inside the fence, `<` and `&` are escaped by the renderer, so nothing the transcript
//     carries can climb out of the code block and become markup.
//
// Stripped silently, and therefore never emitted here: `<script>`, `<style>`, `<iframe>`, inline
// `<svg>`, `class`, and any `style` attribute of our own. Layout is tables, `align` and image
// `width`; there is no CSS to be had. `test/readme.test.ts` asserts that over the file this
// writes rather than over a string a test built itself.
//
// THE FRAGMENT APPROACH IS THE OLD ONE. `#gh-dark-mode-only` / `#gh-light-mode-only` still work
// (the rules are still in GitHub's live stylesheet) but the docs stopped mentioning them, and
// they rely on GitHub auto-linking the image. `<picture>` is the documented mechanism: GA since
// 2022-08-15, and the current docs page still states that the element is supported.
import type { Content } from "./content.ts";
import { esc } from "./rows.ts";

/**
 * The two Theme Variants, at the paths `build` writes them to, relative to the README.
 *
 * Repo-relative and therefore served from `raw.githubusercontent.com` (measured: GitHub rewrites
 * a relative README image to `/<owner>/<repo>/raw/<branch>/<path>`, which redirects there) with a
 * 5-minute cache and a `style-src 'unsafe-inline'` policy, which is what lets the SVG's own
 * `@keyframes` run. It never passes through the camo proxy, whose cache serves hours-old copies
 * of third-party images regardless of what they ask for. Both re-measured 2026-10-02.
 */
export const DARK_SRC = "assets/session-dark.svg";
export const LIGHT_SRC = "assets/session-light.svg";

/**
 * A fence long enough that nothing in `body` can close it early.
 *
 * A blurb holding a backtick run is unlikely rather than impossible, and the failure would be
 * silent in the worst way: the transcript would end mid-Session and the rest of it would render
 * as prose, with the grid gone. CommonMark lets a fence be any run of three or more, and only a
 * run at least as long as the opening one closes it, so one longer than the longest run inside
 * is always safe.
 */
function fence(body: string): string {
  let longest = 0;
  for (const run of body.matchAll(/`+/g)) longest = Math.max(longest, run[0].length);
  return "`".repeat(Math.max(3, longest + 1));
}

/**
 * The README, as text. Every visible word in it is the owner's and comes from `content.json`
 * (docs/spec.md 4.1): the picture's accessible name and the transcript's label are both words a
 * reader hears read aloud, so neither is typed in here. What this file owns is the structure:
 * which element holds what, in which order, and at which paths.
 */
export function renderReadme(o: { content: Content; transcript: string }): string {
  const { imageAlt, transcriptSummary } = o.content.readme;
  const f = fence(o.transcript);
  // The blank lines inside `<details>` are load-bearing, not formatting: without the one after
  // `</summary>` GitHub treats the fence as literal text and the transcript renders as a wall of
  // prose with its columns collapsed.
  return `<!-- Generated by src/readme.ts. Do not edit by hand: change content.json and run npm run build. -->
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="${DARK_SRC}">
  <source media="(prefers-color-scheme: light)" srcset="${LIGHT_SRC}">
  <img src="${DARK_SRC}" alt="${esc(imageAlt)}" width="100%">
</picture>

<details>
<summary>${esc(transcriptSummary)}</summary>

${f}
${o.transcript}
${f}

</details>
`;
}
