// src/readme.ts
//
// The README that carries the Session: one `<picture>` that swaps on the reader's theme, and
// nothing else. `build` writes it; nothing here reads the filesystem or the network.
//
// THE ALT TEXT IS THE ONLY TEXT A READER GETS, AND THAT IS NEW. Until 2026-10-03 the generator
// also wrote the Session out as plain text inside a `<details>` block under the picture, so `alt`
// could be a short pointer at it. The owner deleted that block: nobody opened it, and a collapsed
// disclosure triangle under a full-width picture reads as clutter (ADR 0004, third amendment). So
// `readme.imageAlt` is now the WHOLE accessible content of the profile, and it is one sentence.
// What that sentence says is the owner's, and the trade they made is recorded in ADR 0004 rather
// than argued here: a reader who wants the detail is sent to the repository's `docs/`.
//
// What this file must not do is point at something that is not there. The clause the old string
// ended with, naming a transcript below the picture, was removed with the block it named.
//
// `src/rows.ts` still has `textOnly`, and it is no longer about a reader. The spinner's resting
// verb carries one because `src/build.ts` reads its COLUMN to place the drawn alternatives on top
// of it, and because `rowsToFullText` must see every projection for the ADR 0001 name gate. Both
// of those are unchanged by this; what changed is that nothing downstream publishes the text.
//
// WHAT GITHUB ALLOWS, measured rather than remembered. GitHub sanitises README HTML, and the
// failure mode is invisible: the page still renders, just wrong. Re-verified 2026-10-02 by POSTing
// this exact markup to `https://api.github.com/markdown`, which is GitHub's own renderer behind
// its own sanitiser, and reading back what survived:
//
//   - `<picture>` with `<source media srcset>` survives intact, wrapped in `<themed-picture>`.
//   - `<img src alt width>` survives. GitHub injects `style="max-width: 100%"` itself and
//     auto-wraps the image in a link to its own src.
//   - An HTML comment is removed from the output entirely, so the generated-file notice at the
//     top costs the reader nothing.
//
// That session also measured `<details>`, `<summary>` and a fence inside them, and all three
// survive. `docs/spec.md` 1.1 keeps those rows because they are measurements and re-checkable;
// this file no longer emits any of them, and `scripts/gates.ts` now fails if one comes back.
//
// Stripped silently, and therefore never emitted here: `<script>`, `<style>`, `<iframe>`, inline
// `<svg>`, `class`, and any `style` attribute of our own. Layout is tables, `align` and image
// `width`; there is no CSS to be had. `test/readme.test.ts` asserts that over the file this
// writes rather than over a string a test built itself.
//
// THE FRAGMENT APPROACH IS THE OLD ONE. `#gh-dark-mode-only` / `#gh-light-mode-only` still work
// (the rules are still in GitHub's live stylesheet) but the docs stopped mentioning them, and
// they rely on GitHub auto-linking the image. `<picture>` is the documented mechanism: GA since
// 2022-08-15, and the current docs page still states that the element is supported.
import type { Content } from "./content.ts";
import { esc } from "./rows.ts";

/**
 * The two Theme Variants, at the paths `build` writes them to, relative to the README.
 *
 * Repo-relative and therefore served from `raw.githubusercontent.com` (measured: GitHub rewrites
 * a relative README image to `/<owner>/<repo>/raw/<branch>/<path>`, which redirects there) with a
 * 5-minute cache and a `style-src 'unsafe-inline'` policy, which is what lets the SVG's own
 * `@keyframes` run. It never passes through the camo proxy, whose cache serves hours-old copies
 * of third-party images regardless of what they ask for. Both re-measured 2026-10-02.
 */
export const DARK_SRC = "assets/session-dark.svg";
export const LIGHT_SRC = "assets/session-light.svg";

/**
 * The README, as text. The one visible word in it is the owner's and comes from `content.json`
 * (docs/spec.md 4.1): the picture's accessible name is a sentence a reader hears read aloud, so
 * it is not typed in here. What this file owns is the structure: which element holds what, in
 * which order, and at which paths.
 *
 * There is deliberately no `transcript` parameter any more. It was the only reason this function
 * ever took the Session's text, and taking it while emitting nothing from it would leave a seam
 * that looks like the block is one edit away from coming back.
 */
export function renderReadme(o: { content: Content }): string {
  const { imageAlt } = o.content.readme;
  return `<!-- Generated by src/readme.ts. Do not edit by hand: change content.json and run npm run build. -->
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="${DARK_SRC}">
  <source media="(prefers-color-scheme: light)" srcset="${LIGHT_SRC}">
  <img src="${DARK_SRC}" alt="${esc(imageAlt)}" width="100%">
</picture>
`;
}
